version: '2.1'

services:
  postgresql:
    image: postgres:12.3-alpine
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=leela
    ports:
      - 5433:5432

  postgresql-test:
    image: postgres:12.3-alpine
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=leela
    ports:
      - 25433:5432